name: hydrogen

services:
  bookbear:
    image: vegardege/bookbear:latest
    ports:
      - "3000:3000"
    volumes:
      - bookbear-data:/app/data
    restart: unless-stopped

volumes:
  bookbear-data:
